CCM-10294: temp testing change

diff --git a/.github/workflows/dispatch_internal_repo_workflow.yaml b/.github/workflows/dispatch_internal_repo_workflow.yaml
--- a/.github/workflows/dispatch_internal_repo_workflow.yaml
+++ b/.github/workflows/dispatch_internal_repo_workflow.yaml
@@ -81,72 +81,72 @@ jobs:
             }')
 
           # Trigger The workflow
-          # curl -L \
-          #   --fail \
-          #   --silent \
-          #   -X POST \
-          #   -H "Accept: application/vnd.github+json" \
-          #   -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
-          #   -H "X-GitHub-Api-Version: 2022-11-28" \
-          #   "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/workflows/${{ inputs.targetWorkflow }}/dispatches" \
-          #   -d "${DISPATCH_EVENT}"
+          curl -L \
+            --fail \
+            --silent \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/workflows/${{ inputs.targetWorkflow }}/dispatches" \
+            -d "${DISPATCH_EVENT}"
 
-          # echo "Workflow triggered. Waiting for the workflow to complete.."
+          echo "Workflow triggered. Waiting for the workflow to complete.."
 
-          # # Poll GitHub API to check the workflow status
-          # workflow_run_url=""
-          # for i in {1..12}; do
-          #   workflow_run_url=$(curl -s \
-          #     -H "Accept: application/vnd.github+json" \
-          #     -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
-          #     -H "X-GitHub-Api-Version: 2022-11-28" \
-          #     "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs?event=workflow_dispatch&status=in_progress" \
-          #     | jq -r '.workflow_runs[]
-          #       | select(.name
-          #       | contains("'${{ inputs.targetEnvironment }}'") and
-          #         contains("'${{ inputs.targetAccountGroup }}'") and
-          #         contains("'${{ inputs.targetComponent }}'") and
-          #         contains("'${{ inputs.terraformAction }}'"))
-          #       | .url')
+          # Poll GitHub API to check the workflow status
+          workflow_run_url=""
+          for i in {1..12}; do
+            workflow_run_url=$(curl -s \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              "https://api.github.com/repos/NHSDigital/nhs-notify-internal/actions/runs?event=workflow_dispatch&status=in_progress" \
+              | jq -r '.workflow_runs[]
+                | select(.name
+                | contains("'${{ inputs.targetEnvironment }}'") and
+                  contains("'${{ inputs.targetAccountGroup }}'") and
+                  contains("'${{ inputs.targetComponent }}'") and
+                  contains("'${{ inputs.terraformAction }}'"))
+                | .url')
 
-          #   if [[ -n "$workflow_run_url" && "$workflow_run_url" != null ]]; then
-          #     ui_url=${workflow_run_url/api./}
-          #     ui_url=${ui_url/\/repos/}
-          #     echo "Found workflow run url: $ui_url"
-          #     echo "workflow_run_url=$workflow_run_url" >> $GITHUB_ENV
-          #     break
-          #   fi
+            if [[ -n "$workflow_run_url" && "$workflow_run_url" != null ]]; then
+              ui_url=${workflow_run_url/api./}
+              ui_url=${ui_url/\/repos/}
+              echo "Found workflow run url: $ui_url"
+              echo "workflow_run_url=$workflow_run_url" >> $GITHUB_ENV
+              break
+            fi
 
-          #   echo "Waiting for workflow to start..."
-          #   sleep 10
-          # done
+            echo "Waiting for workflow to start..."
+            sleep 10
+          done
 
-          # if [[ -z "$workflow_run_url" || "$workflow_run_url" == null ]]; then
-          #   echo "Failed to get the workflow run url. Exiting."
-          #   exit 1
-          # fi
+          if [[ -z "$workflow_run_url" || "$workflow_run_url" == null ]]; then
+            echo "Failed to get the workflow run url. Exiting."
+            exit 1
+          fi
 
-          # # Wait for workflow completion
-          # while true; do
-          #   sleep 10
-          #   response=$(curl -s -L \
-          #     -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
-          #     -H "Accept: application/vnd.github+json" \
-          #     $workflow_run_url)
+          # Wait for workflow completion
+          while true; do
+            sleep 10
+            response=$(curl -s -L \
+              -H "Authorization: Bearer ${{ secrets.PR_TRIGGER_PAT }}" \
+              -H "Accept: application/vnd.github+json" \
+              $workflow_run_url)
 
-          #   status=$(echo "$response" | jq -r '.status')
-          #   conclusion=$(echo "$response" | jq -r '.conclusion')
+            status=$(echo "$response" | jq -r '.status')
+            conclusion=$(echo "$response" | jq -r '.conclusion')
 
-          #   if [ "$status" == "completed" ]; then
-          #     if [ "$conclusion" == "success" ]; then
-          #       echo "Workflow completed successfully."
-          #       exit 0
-          #     else
-          #       echo "Workflow failed with conclusion: $conclusion"
-          #       exit 1
-          #     fi
-          #   fi
+            if [ "$status" == "completed" ]; then
+              if [ "$conclusion" == "success" ]; then
+                echo "Workflow completed successfully."
+                exit 0
+              else
+                echo "Workflow failed with conclusion: $conclusion"
+                exit 1
+              fi
+            fi
 
-          #   echo "Workflow still running..."
-          #   sleep 20
-          # done
+            echo "Workflow still running..."
+            sleep 20
+          done
