CCM-11027: add proper increment logic

diff --git a/.github/workflows/stage-1-commit.yaml b/.github/workflows/stage-1-commit.yaml
--- a/.github/workflows/stage-1-commit.yaml
+++ b/.github/workflows/stage-1-commit.yaml
@@ -225,6 +225,7 @@ jobs:
           fi
 
   check-schemas-generated:
+    name: Check event schemas have been regenerated
     needs: detect-event-schema-package-changes
     if: needs.detect-event-schema-package-changes.outputs.changed == 'true'
     runs-on: ubuntu-latest
@@ -242,6 +243,7 @@ jobs:
         run: git diff --quiet packages/event-schemas/schemas
 
   check-schema-version-change:
+    name: Check event schema version has been updated
     needs: detect-event-schema-package-changes
     if: needs.detect-event-schema-package-changes.outputs.changed == 'true'
     runs-on: ubuntu-latest
@@ -260,9 +262,15 @@ jobs:
 
       - name: Check schema versions
         run: |
-          published_version=$(npm view @nhsdigital/nhs-notify-event-schemas-template-management --json 2>/dev/null | jq -r '.["dist-tags"].latest')
-          local_version=$(cat packages/event-schemas/package.json | jq -r '.version')
-          if [[ $published_version != "null" && $local_version = $published_version ]]; then
-            echo "Error: Event Schema package has changed, but version has not been incremented. Latest published version is $published_version, local version is $local_version."
+          source scripts/is_valid_increment.sh
+
+          published_version=$(npm view @nhsdigital/nhs-notify-event-schemas-template-management --json 2>/dev/null | jq -r '.["dist-tags"].latest // "null"')
+          echo "Published version: $published_version"
+
+          local_version=$(jq -r '.version' packages/event-schemas/package.json)
+          echo "Local version: $local_version"
+
+          if ! is_valid_increment "$published_version" "$local_version" ; then
+            echo "Error: Event Schema package has changed, but new version $local_version is not a valid increment from latest published version $published_version."
             exit 1
           fi
